apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-crt
spec:
  secretName: tls-secret
  duration: 384h
  renewBefore: 72h
  issuerRef:
    kind: Issuer
    name: selfsigned
  commonName: "k8scertmonitor.local"
  isCA: false
  dnsNames:
    - "k8scertmonitor.local"