apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-cert-monitor.fullname" . }}
  labels:
    {{- include "k8s-cert-monitor.labels" . | nindent 4 }}
    app: k8s-cert-monitor
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "k8s-cert-monitor.selectorLabels" . | nindent 4 }}
    app: k8s-cert-monitor
